library(readr)
Theft_Data <- read_csv("C:/Users/Nishank/Desktop/SNU/RStuff/Theft Data.csv")
View(Theft_Data)
names(Theft_Data)
library(tidyverse)
Theft_Data<-select(Theft_Data,(1:6))
names(Theft_Data)
table(Theft_Data$Name)
ggplot(Theft_Data,mapping = aes(x = Name, y = Total)) + geom_col() + facet_wrap(~Year)

theftModel<-lm(Total~Year + Name, data = Theft_Data)
summary(theftModel)
plot(theftModel$residuals)
qqnorm(theftModel$residuals)
qqline(theftModel$residuals)
hist(theftModel$residuals)
